name: Build and deploy Node.js app to Azure Web App - QuaDAO-app
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: 'Install Truffle and OpenZeppelin Contracts'
        run: |
          npm install
          npm install -g truffle
          npm install @openzeppelin/contracts
      - name: Deploying to Sepolia
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }} 
        run: |
          truffle migrate --network sepolia --reset
      - name: 'React Dapp build'
        run: |
          npm run build
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          app-name: 'QuadraDAO-app'
          slot-name: 'production'
          package: './build'
  